models/Usuarios.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\helpers\Security;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "usuarios".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $usuario
 * @property string $clave
 * @property string $estatus
 */
class Usuarios extends \yii\db\ActiveRecord implements IdentityInterface

{
    public $clave_repeat;
    public $auth_key;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usuarios';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'usuario', 'clave', 'estatus'], 'required'],
            [['id'], 'integer'],
            [['estatus'], 'string'],
            [['clave'], 'compare', 'message'=>"Las contraseñas deben coincidir", 'on'=>['insert','reset']],
            [['nombre'], 'string', 'max' => 255],
            [['usuario'], 'string', 'max' => 50],
            [['clave'], 'string', 'max' => 45],
            [['clave_repeat'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            // 'id' => 'ID',
            'nombre' => 'Nombre',
            'usuario' => 'Usuario',
            'clave' => 'Contraseña',
            'clave_repeat' => 'Repita su contraseña',
            'estatus' => 'Estatus',
        ];
    }
    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['usuario' => $username]);
    }

            /**
     * @inheritdoc
     */
        public static function findIdentity($id)
        {
            return static::findOne($id);
        }

            /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

           /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return hash('md5', $password)=== $this->clave;
    }    

       /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Security::generatePasswordHash($password);
    }

    public function beforeSave($insert)
    {
        $return = parent::beforeSave($insert);
        $this->clave = hash('md5',$this->clave);
        return $return;
    }

        public static function findIdentityByAccessToken($token, $type = null)
    {
          return static::findOne(['access_token' => $token]);
    }
      /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }
        /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

        /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Security::generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Security::generateRandomKey() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

controllers/UsuariosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Usuarios;
use app\models\LoginForm;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * UsuariosController implements the CRUD actions for Usuarios model.
 */
class UsuariosController extends Controller
{
    public $layout="admin";
    
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
                ],
            'access' => [ 
                'class' => AccessControl::className(), 
                'rules' => [
                        ['roles' => ['?'], 'allow' => false, ],
                        ['roles' => ['@'], 'allow' => true, ],
                        ['actions'=>['login'], 'roles' => ['?'], 'allow' => true, ],
                        ['actions' => ['logout'], 'roles' => ['@'], 'allow' => true, ]
                    ]
            ]            
        ];
    }

    /**
     * Lists all Usuarios models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Usuarios::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Usuarios model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Usuarios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Usuarios();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Usuarios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Usuarios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Usuarios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Usuarios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Usuarios::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Renderiza el formulario de logeo.
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) 
            return $this->redirect(['noticias/index']);
        $model=new LoginForm();
        if ($model->load(Yii::$app->request->post()) and $model->login()) {
            # Entra a la validacion de cuenta
            return $this->redirect(['noticias/index']);
        }
        #Rederiza el formulario.
        return $this->render('login',compact('model'));
    }

    public function actionResetear($id)
    {
        # Cambia la contraseña
        $model=$this->findModel($id);
        if ($model->load(Yii::$app->request->post()) ) {
            $model->scenario="reset";
            # Entra a la validacion de cuenta
            if ($model->validate()) {
                # Si las contraseñas coinciden 
                    $model->save();
                    return $this->redirect(['index']);
            }

        }
        return $this->render('_reseteo',compact('model'));       
        #Rederiza el formulario.
    }

    public function actionConfig()
    {
        # Se encarga de cambiar el fondo de la pagina
        if (!empty($_POST)) {
            echo "<div class='alert'> Se subio la imagen </div>";
            $archivo= UploadedFile::getInstanceByName('imagen');
                if (!empty($archivo)) {
                # Si se subio una imagen
                    $archivo->saveAs('images/fondo.jpg'); 
                }
            }
            return $this->render('configuraciones');       

    }
}

views/usuarios/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Usuarios */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="usuarios-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'usuario')->textInput(['maxlength' => 50]) ?>

    <?= $model->isNewRecord ?$form->field($model, 'clave')->passwordInput(['maxlength' => 45]): ''; ?>
    <?= $model->isNewRecord ?$form->field($model, 'clave_repeat')->passwordInput(['maxlength' => 45]): ''; ?>

    <?= $form->field($model, 'estatus')->dropDownList([ 'ALTA' => 'ALTA', 'BAJA' => 'BAJA', ], []) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar cambios', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/usuarios/_reseteo.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Usuarios */
/* @var $form yii\widgets\ActiveForm */
?>

    <?php $form = ActiveForm::begin(); ?>
<div class="login-form form-signin">
<h1>Reseteo de contraseña</h1>

    <?= $form->field($model, 'clave')->passwordInput(['maxlength' => 45]) ?>
    <?= $form->field($model, 'clave_repeat')->passwordInput(['maxlength' => 45]) ?>

    <br>
    <div class="form-group">
        <?= Html::submitButton('Cambiar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/usuarios/configuraciones.php
<?php 
use yii\helpers\Html;

 ?>
    <?= Html::beginForm('','post',['enctype' => 'multipart/form-data']); ?>

<div class="login-form form-signin">
<h2>Configuraciones generales</h2>
<div class="panel panel-default body" >
  <div class="panel-heading">Imagen de fondo del sitio</div>
  <div class="panel-body">
    <?= Html::fileInput('imagen'); ?>
  </div>
</div>

    <br>
    <div class="form-group">
        <?= Html::submitButton('Aplicar', ['class' => 'btn btn-primary']) ?>
    </div>
    <?= Html::endForm(); ?>


</div>

views/usuarios/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Usuarios */

$this->title = 'Nuevo Usuario';
$this->params['breadcrumbs'][] = ['label' => 'Usuarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usuarios-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/usuarios/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Usuarios';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usuarios-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Nuevo Usuario', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nombre',
            'usuario',
            'estatus',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/usuarios/login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Usuarios */
/* @var $form yii\widgets\ActiveForm */
?>

    <?php $form = ActiveForm::begin(); ?>
    <?php echo $form->errorSummary($model,['header'=>'Por favor corriga lo siguiente:']); ?>
<div class="login-form form-signin">
<h1>Inicio de sesion</h1>

    <?= $form->field($model, 'username')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => 45]) ?>
    <?= $form->field($model, 'rememberMe', [
        ])->checkbox() ?>
    <br>
    <div class="form-group">
        <?= Html::submitButton('Validar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<style type="text/css">
    
    body {
  padding-top: 40px;
  padding-bottom: 40px;

}
.form-signin {background: #efefef}
.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-signin-heading,
.form-signin .checkbox {
  margin-bottom: 10px;
}
.form-signin .checkbox {
  font-weight: normal;
}
.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
</style>

views/usuarios/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Usuarios */

$this->title = 'Actualizar datos del Usuario: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Usuarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="usuarios-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
<?= Html::a('Cambiar contraseña', ['usuarios/resetear','id'=>$model->id],['class'=>"btn"]) ?>
</div>

views/usuarios/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Usuarios */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Usuarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usuarios-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar datos', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¡Esta usted seguro de querer eliminar a este usuario?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'usuario',
            'estatus',
        ],
    ]) ?>

</div>