models/Anunciantes.php
<?php

namespace app\models;

    use Yii;
    use yii\helpers\Html;
use yii\web\UploadedFile;


/**
 * This is the model class for table "anunciantes".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property string $estatus
 * @property string $categorias
 * @property string $logo
 */
class Anunciantes extends \yii\db\ActiveRecord
{
    public $categorias_array;
    public $archivo_imagen;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'anunciantes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'descripcion', 'estatus'], 'required', 'message'=>'El {attribute} no se puede dejar vacio'],
            [['descripcion', 'estatus'], 'string'],
            [['logo'], 'file'],
            [['categorias_array','categorias'], 'safe'],
            [['nombre'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'descripcion' => 'Descripcion',
            'estatus' => 'Estatus',
            'categorias' => 'Categorias',
            'logo' => 'Logo',
        ];
    }

    public function afterFind()
    {
                parent::afterFind();
                $this->categorias_array=explode(',',$this->categorias);

    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
        // ...custom code here...
            if (!empty($this->categorias_array)) {
                # Si se seleccionaron categorias se guardan como un texto plano separado por comas
                $this->categorias=implode(',', $this->categorias_array);
            }
            return true;
        } else {
            return false;
        }    
    }

    public function getImagenLogo()
    {
        # regresa la imagen del logo
        return Html::img(Yii::getAlias('@web/images/'.$this->logo),['class'=>'img-thumbnail']);
    }

    public function getCategorias()
    {
        # regresa un arreglo de categorias dependiendo de los ids separados por comas
        $ids=explode(',', $this->categorias);
        if (!empty($ids)) {
            # Si se le han especificado ids de categorias
            return Categorias::find($ids);
        }else{
            return [];
        }
    }



   /**
     * Devuelve el contenido sin html en los primeros n caracteres
     */
    public function getContenido()
    {
        return substr(strip_tags($this->descripcion),0,250);
    }
}

controllers/AnunciantesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Anunciantes;
use app\models\BuscadorAnunciantes;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * AnunciantesController implements the CRUD actions for Anunciantes model.
 */
class AnunciantesController extends Controller
{
    public $layout="admin";
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [ 
                'class' => AccessControl::className(), 
                'rules' => [
                        ['roles' => ['?'], 'allow' => false, ],
                        ['roles' => ['@'], 'allow' => true, ],
                    ]
            ]              
        ];
    }

    /**
     * Lists all Anunciantes models.
     * @return mixed
     */
 public function actionIndex()
    {
        $searchModel = new BuscadorAnunciantes();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionBuscar()
    {
        $searchModel = new BuscadorAnunciantes();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->renderPartial('_resultados', [
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Displays a single Anunciantes model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Anunciantes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Anunciantes();

        if ($model->load(Yii::$app->request->post())) {
                # Se sube el archivo y se le asigna al atributo
            $model->logo = UploadedFile::getInstance($model, 'logo');
            // var_dump($model->logo);
            if ($model->validate()) {                
                if (is_object($model->logo)) {
                    # Si se logra instanciar al modelo de uploadfile
                    $model->logo->saveAs('images/' . $model->logo->baseName . '.' . $model->logo->extension);
                }                  
            }            

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
            else
                return $this->render('create', [
                    'model' => $model,
                    ]);
        } 
        else {
            return $this->render('create', [
                'model' => $model,
                ]);
        }
    }

    /**
     * Updates an existing Anunciantes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->archivo_imagen = UploadedFile::getInstance($model, 'archivo_imagen');
            // var_dump($model->archivo_imagen);
            if ($model->validate()) { 
                if (!empty($model->archivo_imagen)) {
                # Si se subio una imagen
                    $nombre=hash('md5',$model->archivo_imagen->baseName . '.' . $model->archivo_imagen->extension);
                    $model->archivo_imagen->saveAs('images/' . $nombre); 
                    $model->logo=$nombre;
                }
            }               
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
            else
                return $this->render('update', [
                    'model' => $model,
                    ]);
        } else {
            return $this->render('update', [
                'model' => $model,
                ]);
        }
    }

    /**
     * Deletes an existing Anunciantes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Anunciantes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Anunciantes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Anunciantes::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/anunciantes/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\tinymce\TinyMce;
use app\models\Categorias;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model app\models\Anunciantes */
/* @var $form yii\widgets\ActiveForm */

$categorias=Categorias::find()->all();
?>

<div class="anunciantes-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => 200]) ?>

<?= $form->field($model, 'descripcion')->textArea(['rows' => '6']); ?>
<?php 
//  $form->field($model, 'text')->widget(TinyMce::className(), [
//     'options' => ['rows' => 6],
//     'language' => 'es',
//     'clientOptions' => [
//         'plugins' => [
//             "advlist autolink lists link charmap print preview anchor",
//             "searchreplace visualblocks code fullscreen",
//             "insertdatetime media table contextmenu paste"
//         ],
//         'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
//     ]
// ]);
 ?>
    <?= $form->field($model, 'estatus')->dropDownList([ 'ALTA' => 'ALTA', 'BAJA' => 'BAJA', ], []) ?>
    <?= $form->field($model, 'categorias_array')->dropDownList(
    ArrayHelper::map($categorias,'id','nombre'), ['multiple' => true]) ?>

    <?= $form->field($model, 'archivo_imagen')->fileInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar cambios', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php 
$this->registerJs("
$('#anunciantes-categorias_array').prop('multiple',true);
    $('#anunciantes-categorias_array').chosen({width: '95%'})");
 ?>

views/anunciantes/_resultados.php
<?php 
use yii\grid\GridView;
?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summary'=>'',
        'columns' => [
            // ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            'nombre',
            'contenido:ntext',
            // 'estatus',
            // 'categorias',
            'imagenLogo:html',

            // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

views/anunciantes/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BuscadorAnunciantes */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="anunciantes-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'descripcion') ?>

    <?= $form->field($model, 'estatus') ?>

    <?= $form->field($model, 'categorias') ?>

    <?php // echo $form->field($model, 'logo') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/anunciantes/buscador.php
                            <?= 
                            GridView::widget([
                            'dataProvider' => $dataProvider,
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'],

                                'id',
                                'nombre',
                                'descripcion:ntext',
                                'estatus',
                                'categorias',
                                'logo',

                                ['class' => 'yii\grid\ActionColumn'],
                            ],
                        ]); ?>

views/anunciantes/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Anunciantes */

$this->title = 'Nuevo Anunciante';
$this->params['breadcrumbs'][] = ['label' => 'Anunciantes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="anunciantes-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/anunciantes/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Anunciantes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="anunciantes-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Nuevo Anunciante', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nombre',
            'descripcion:ntext',
            'estatus',
            'categorias',
            // 'logo',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/anunciantes/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Anunciantes */

$this->title = 'Actualizar Anunciante: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Anunciantes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="anunciantes-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/anunciantes/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Anunciantes */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Anunciantes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="anunciantes-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Esta usted seguro de eliminar a este anunciante?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'descripcion:ntext',
            'estatus',
            'categorias',
            'logo',
            'imagenLogo:html',
        ],
    ]) ?>

</div>

views/anunciantes/widget.php
<?php 
use app\models\Categorias;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use kartik\popover\PopoverX;
echo  Html::tag('div',
	Html::textInput('Anunciantes[nombre]','',
		[
		'placeholder'=>'Nombre del anunciante',
		'class'=>'form-control',
		'style'=>'width:70%;display:inline',
		'id'=>'Anunciantes_nombre'
		]).
	Html::a('Buscar',['anunciantes/buscar'],[
		'class'=>'btn btn-info',
		'id'=>'buscar_anunciantes'
		])
	,['class'=>'col-xs-7 col-center']);
echo "<br>";
echo Html::tag('div','',['id'=>'Anunciantes_resultados']);
$listaCatego=Categorias::find()->orderBy('estatus desc')->limit(3)->all();
foreach ($listaCatego as $catego) {
	 // echo '<div>',$catego->nombre,' ' ;
	 echo Html::beginTag('div',array('class'=>'col-xs-4 col-md-4'));
	 echo '<div class="panel panel-default"> <div class="panel-body">';
	 echo Html::beginTag('ul',array('class'=>'nav nav-pills nav-stacked'));
	 $items=[];
	 $items[]=['label'=>$catego->nombre,'class'=>'active'];
	 echo Html::tag('li',Html::a($catego->nombre,'#'),['class'=>'active','role'=>'presentation']);
	 foreach ($catego->anunciantes as $anunciante) {
	 	# Por cada anunciante de cada categoria
	 	$widget= PopoverX::widget([
	 		'header' => $anunciante->nombre,
	 		'placement' => PopoverX::ALIGN_TOP,
	 		'content' =>$anunciante->descripcion,
	 		'toggleButton' => ['label'=>$anunciante->nombre, 'class'=>'btn-link'],
	 		]);
	 	echo Html::tag('li',$widget,['role'=>'presentation']);
	 	// $items[]=['label'=>$anunciante->nombre,'url'=>'#anunciantes'];
	 }
	 echo Html::endTag('ul');
	 echo '</div> </div>';
	 echo Html::endTag('div');
}

 ?>